/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as BakeryRouteImport } from './routes/bakery'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as CatalogRouteImport } from './routes/catalog'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DeliRouteImport } from './routes/deli'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as LoginRouteImport } from './routes/login'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as StoreRouteImport } from './routes/store'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as WholesaleRouteImport } from './routes/wholesale'
import { Route as DepartmentsSlugRouteImport } from './routes/departments.$slug'
import { Route as ProductProductIdRouteImport } from './routes/product.$productId'
import { Route as WholesaleIndexRouteImport } from './routes/wholesale.index'
import { Route as WholesaleProductIdRouteImport } from './routes/wholesale.$productId'
import { Route as WholesaleCatalogRouteImport } from './routes/wholesale.catalog'
import { Route as WholesaleOffersRouteImport } from './routes/wholesale.offers'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const BakeryRoute = BakeryRouteImport.update({
  id: '/bakery',
  path: '/bakery',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const CatalogRoute = CatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliRoute = DeliRouteImport.update({
  id: '/deli',
  path: '/deli',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const StoreRoute = StoreRouteImport.update({
  id: '/store',
  path: '/store',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleRoute = WholesaleRouteImport.update({
  id: '/wholesale',
  path: '/wholesale',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsSlugRoute = DepartmentsSlugRouteImport.update({
  id: '/departments/$slug',
  path: '/departments/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductProductIdRoute = ProductProductIdRouteImport.update({
  id: '/product/$productId',
  path: '/product/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const WholesaleIndexRoute = WholesaleIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WholesaleRoute,
} as any)
const WholesaleProductIdRoute = WholesaleProductIdRouteImport.update({
  id: '/$productId',
  path: '/$productId',
  getParentRoute: () => WholesaleRoute,
} as any)
const WholesaleCatalogRoute = WholesaleCatalogRouteImport.update({
  id: '/catalog',
  path: '/catalog',
  getParentRoute: () => WholesaleRoute,
} as any)
const WholesaleOffersRoute = WholesaleOffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => WholesaleRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bakery': typeof BakeryRoute
  '/careers': typeof CareersRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/deli': typeof DeliRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRouteWithChildren
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/wholesale/$productId': typeof WholesaleProductIdRoute
  '/wholesale/catalog': typeof WholesaleCatalogRoute
  '/wholesale/offers': typeof WholesaleOffersRoute
  '/wholesale/': typeof WholesaleIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bakery': typeof BakeryRoute
  '/careers': typeof CareersRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/deli': typeof DeliRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/wholesale/$productId': typeof WholesaleProductIdRoute
  '/wholesale/catalog': typeof WholesaleCatalogRoute
  '/wholesale/offers': typeof WholesaleOffersRoute
  '/wholesale': typeof WholesaleIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/bakery': typeof BakeryRoute
  '/careers': typeof CareersRoute
  '/catalog': typeof CatalogRoute
  '/contact': typeof ContactRoute
  '/deli': typeof DeliRoute
  '/faq': typeof FaqRoute
  '/login': typeof LoginRoute
  '/notifications': typeof NotificationsRoute
  '/offers': typeof OffersRoute
  '/store': typeof StoreRoute
  '/terms': typeof TermsRoute
  '/wholesale': typeof WholesaleRouteWithChildren
  '/departments/$slug': typeof DepartmentsSlugRoute
  '/product/$productId': typeof ProductProductIdRoute
  '/wholesale/$productId': typeof WholesaleProductIdRoute
  '/wholesale/catalog': typeof WholesaleCatalogRoute
  '/wholesale/offers': typeof WholesaleOffersRoute
  '/wholesale/': typeof WholesaleIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/bakery'
    | '/careers'
    | '/catalog'
    | '/contact'
    | '/deli'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/store'
    | '/terms'
    | '/wholesale'
    | '/departments/$slug'
    | '/product/$productId'
    | '/wholesale/$productId'
    | '/wholesale/catalog'
    | '/wholesale/offers'
    | '/wholesale/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/bakery'
    | '/careers'
    | '/catalog'
    | '/contact'
    | '/deli'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/store'
    | '/terms'
    | '/departments/$slug'
    | '/product/$productId'
    | '/wholesale/$productId'
    | '/wholesale/catalog'
    | '/wholesale/offers'
    | '/wholesale'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/bakery'
    | '/careers'
    | '/catalog'
    | '/contact'
    | '/deli'
    | '/faq'
    | '/login'
    | '/notifications'
    | '/offers'
    | '/store'
    | '/terms'
    | '/wholesale'
    | '/departments/$slug'
    | '/product/$productId'
    | '/wholesale/$productId'
    | '/wholesale/catalog'
    | '/wholesale/offers'
    | '/wholesale/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BakeryRoute: typeof BakeryRoute
  CareersRoute: typeof CareersRoute
  CatalogRoute: typeof CatalogRoute
  ContactRoute: typeof ContactRoute
  DeliRoute: typeof DeliRoute
  FaqRoute: typeof FaqRoute
  LoginRoute: typeof LoginRoute
  NotificationsRoute: typeof NotificationsRoute
  OffersRoute: typeof OffersRoute
  StoreRoute: typeof StoreRoute
  TermsRoute: typeof TermsRoute
  WholesaleRoute: typeof WholesaleRouteWithChildren
  DepartmentsSlugRoute: typeof DepartmentsSlugRoute
  ProductProductIdRoute: typeof ProductProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bakery': {
      id: '/bakery'
      path: '/bakery'
      fullPath: '/bakery'
      preLoaderRoute: typeof BakeryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/catalog': {
      id: '/catalog'
      path: '/catalog'
      fullPath: '/catalog'
      preLoaderRoute: typeof CatalogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deli': {
      id: '/deli'
      path: '/deli'
      fullPath: '/deli'
      preLoaderRoute: typeof DeliRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/store': {
      id: '/store'
      path: '/store'
      fullPath: '/store'
      preLoaderRoute: typeof StoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale': {
      id: '/wholesale'
      path: '/wholesale'
      fullPath: '/wholesale'
      preLoaderRoute: typeof WholesaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments/$slug': {
      id: '/departments/$slug'
      path: '/departments/$slug'
      fullPath: '/departments/$slug'
      preLoaderRoute: typeof DepartmentsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$productId': {
      id: '/product/$productId'
      path: '/product/$productId'
      fullPath: '/product/$productId'
      preLoaderRoute: typeof ProductProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/wholesale/': {
      id: '/wholesale/'
      path: '/'
      fullPath: '/wholesale/'
      preLoaderRoute: typeof WholesaleIndexRouteImport
      parentRoute: typeof WholesaleRoute
    }
    '/wholesale/$productId': {
      id: '/wholesale/$productId'
      path: '/$productId'
      fullPath: '/wholesale/$productId'
      preLoaderRoute: typeof WholesaleProductIdRouteImport
      parentRoute: typeof WholesaleRoute
    }
    '/wholesale/catalog': {
      id: '/wholesale/catalog'
      path: '/catalog'
      fullPath: '/wholesale/catalog'
      preLoaderRoute: typeof WholesaleCatalogRouteImport
      parentRoute: typeof WholesaleRoute
    }
    '/wholesale/offers': {
      id: '/wholesale/offers'
      path: '/offers'
      fullPath: '/wholesale/offers'
      preLoaderRoute: typeof WholesaleOffersRouteImport
      parentRoute: typeof WholesaleRoute
    }
  }
}

interface WholesaleRouteChildren {
  WholesaleProductIdRoute: typeof WholesaleProductIdRoute
  WholesaleCatalogRoute: typeof WholesaleCatalogRoute
  WholesaleOffersRoute: typeof WholesaleOffersRoute
  WholesaleIndexRoute: typeof WholesaleIndexRoute
}

const WholesaleRouteChildren: WholesaleRouteChildren = {
  WholesaleProductIdRoute: WholesaleProductIdRoute,
  WholesaleCatalogRoute: WholesaleCatalogRoute,
  WholesaleOffersRoute: WholesaleOffersRoute,
  WholesaleIndexRoute: WholesaleIndexRoute,
}

const WholesaleRouteWithChildren = WholesaleRoute._addFileChildren(
  WholesaleRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BakeryRoute: BakeryRoute,
  CareersRoute: CareersRoute,
  CatalogRoute: CatalogRoute,
  ContactRoute: ContactRoute,
  DeliRoute: DeliRoute,
  FaqRoute: FaqRoute,
  LoginRoute: LoginRoute,
  NotificationsRoute: NotificationsRoute,
  OffersRoute: OffersRoute,
  StoreRoute: StoreRoute,
  TermsRoute: TermsRoute,
  WholesaleRoute: WholesaleRouteWithChildren,
  DepartmentsSlugRoute: DepartmentsSlugRoute,
  ProductProductIdRoute: ProductProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
